### ISSUE TITLE
Support for additional data ordering formats

### ISSUE THREAD

**Issue by ahundt** [tanyaschlusser/array2gif#1]
This API looks fairly simple to use & convenient but could you consider adding one small convenience feature?

I tried inputting a 4d numpy array and got the following:
```
Processing /home/cpaxton/.costar/data/2018-04-24-14-19-15_example000001.failure.h5f:   0%| | 0/454 [00:00<?, ?it/s]Traceback (most recent call last):
  File "scripts/make_gif.py", line 78, in <module>
    main(args)
  File "scripts/make_gif.py", line 74, in main
    write_gif(images, gif_filename, fps=10)
  File "/home/cpaxton/.local/lib/python2.7/site-packages/array2gif/core.py", line 361, in write_gif
    check_dataset(dataset)
  File "/home/cpaxton/.local/lib/python2.7/site-packages/array2gif/core.py", line 56, in check_dataset
    check_dataset_shape(dataset)
  File "/home/cpaxton/.local/lib/python2.7/site-packages/array2gif/core.py", line 45, in check_dataset_shape
    raise ValueError('The dataset needs 3 dimensions: rgb, nrows, ncols')
ValueError: The dataset needs 3 dimensions: rgb, nrows, ncols
Exception KeyError: KeyError(<weakref at 0x7fe647f1fd08; to 'tqdm' at 0x7fe6634d8910>,) in <bound method tqdm.__del__ of Processing /home/cpaxton/.costar/data/2018-04-24-14-19-15_example000001.failure.h5f:   0%| | 0/454 [00:00<?, ?it/s]> ignored
cpaxton@babylon:~/catkin_ws/src/costar_plan/ctp_integration$ 

```

I then tried a list of 3d numpy arrays with jpeg images decoded into numpy arrays in the standard format output by pillow (PIL) and got the following:
```
1.failure.h5f:   0%| | 0/453 [00:00<?, ?it/s]Traceback (most recent call last):
  File "scripts/make_gif.py", line 78, in <module>
    main(args)
  File "scripts/make_gif.py", line 74, in main
    write_gif(images, gif_filename, fps=10)
  File "/home/cpaxton/.local/lib/python2.7/site-packages/array2gif/core.py", line 361, in write_gif
    check_dataset(dataset)
  File "/home/cpaxton/.local/lib/python2.7/site-packages/array2gif/core.py", line 71, in check_dataset
    .format(err, i)
ValueError: The dataset's first dimension must have all 3

```

Here is some code you can use to test if you have two jpegs lying around:
```python

def JpegToNumpy(jpeg):
    stream = io.BytesIO(jpeg)
    im = Image.open(stream)
    return np.asarray(im, dtype=np.uint8)

def ConvertJpegListToNumpy(data, format='numpy'):
    """ Convert a list of binary jpeg files to numpy format.

    # Arguments

    data: a list of binary jpeg images to convert
    format: default 'numpy' returns a 4d numpy array, 
        'list' returns a list of 3d numpy arrays
    """
    length = len(data)
    imgs = []
    for raw in data:
        imgs.append(JpegToNumpy(raw))
    if format == 'numpy':
        imgs = np.array(imgs)
    return imgs

```

Is there any chance you can add support for:
- list of 3d numpy arrays in the default pil format (HWC)
- 4d numpy formats

    - NHWC (number of images, height, width, channels)
         - most common way to store images in numpy arrays
    - NCWH (number of images, channels, height, width)
        - second most common

Each of those is probably only a couple lines, plus perhaps a `data_format` parameter.

**Comment by tanyaschlusser** [comment]
Thank you! Cool! I just got back from PyCon (which was great) and just noticed this issue, so sorry for the delay.

I will try your code and also look up HWC...and ping back. Always thankful for good input 👍 .

**Comment by tanyaschlusser** [comment]
Thank you for your helpful feedback @ahundt! The updated package is now on [pypi](http://pypi.org/project/array2gif). For the record, the newer versions of Pillow also have animated gif output (here's a [link to their docs on it](http://pillow.readthedocs.io/en/3.0.x/handbook/image-file-formats.html#saving-sequences)) but thank you for taking the time on this one. 🎉 🌟

**Comment by ahundt** [comment]
cool, thanks!
