### ISSUE TITLE
error: required argument is not an integer

### ISSUE THREAD

**Issue by alvarouc** [tanyaschlusser/array2gif#3]
I have an array of shape (60, 3, 428, 1184) in the format (frame, rgb, row, column)

When I do
    write_gif([np.squeeze(big[ii,:,:,:]) for ii in range(n_frames)], 'video.gif', fps=30)

I get the error 
```

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-50-497aa6684826> in <module>()
      1 from array2gif import write_gif
      2 
----> 3 write_gif([np.squeeze(big[ii,:,:,:]) for ii in range(n_frames)], 'echo_filter.gif', fps=30)

/opt/virtualenvs/echo_outcome/lib/python3.6/site-packages/array2gif/core.py in write_gif(dataset, filename, fps)
    395     with open(filename, 'wb') as outfile:
    396         outfile.write(HEADER)
--> 397         for block in encode(dataset):
    398             outfile.write(block)
    399         outfile.write(TRAILER)

/opt/virtualenvs/echo_outcome/lib/python3.6/site-packages/array2gif/core.py in _make_animated_gif(datasets, delay_time)
    345 
    346 def _make_animated_gif(datasets, delay_time=10):
--> 347     images = [get_image(d) for d in datasets]
    348     color_sets = (get_colors(image) for image in images)
    349     colors = Counter()

/opt/virtualenvs/echo_outcome/lib/python3.6/site-packages/array2gif/core.py in <listcomp>(.0)
    345 
    346 def _make_animated_gif(datasets, delay_time=10):
--> 347     images = [get_image(d) for d in datasets]
    348     color_sets = (get_colors(image) for image in images)
    349     colors = Counter()

/opt/virtualenvs/echo_outcome/lib/python3.6/site-packages/array2gif/core.py in get_image(dataset)
    104             )
    105             for j in range(ncol)]
--> 106         for i in range(nrow)]
    107     return image
    108 

/opt/virtualenvs/echo_outcome/lib/python3.6/site-packages/array2gif/core.py in <listcomp>(.0)
    104             )
    105             for j in range(ncol)]
--> 106         for i in range(nrow)]
    107     return image
    108 

/opt/virtualenvs/echo_outcome/lib/python3.6/site-packages/array2gif/core.py in <listcomp>(.0)
    103                 dataset[2, i, j]
    104             )
--> 105             for j in range(ncol)]
    106         for i in range(nrow)]
    107     return image

error: required argument is not an integer
```

**Comment by tanyaschlusser** [comment]
Wow, thank you for reporting this! I am able to reproduce your error even with relatively small image sizes. Let me look at what is happening.

Also, the API allows for 4-D numpy arrays now (1.0.3) so you could (hopefully once this is fixed) just write `write_gif(big, 'video.gif', fps=30)`.

**Comment by tanyaschlusser** [comment]
This may take some time to fix...

I have a hunch this is a palette problem: I know for sure I don't attempt to implement a Local Color Table for each frame in the GIF. This means that as the code is written, the document can contain at most 512 unique colors. (per the [GIF89 spec](https://www.w3.org/Graphics/GIF/spec-gif89a.txt) it can be up to 512 unique colors per frame).

I want to confirm this, and then think about a smart way to add local palettes if necessary without bloating the file by doing a whole new one for each frame. Will post back.

**Comment by alvarouc** [comment]
making the input data type 'uint8' solved the problem. Perhaps you should check that the input data type is uint8 and throw an error at it.

**Comment by tanyaschlusser** [comment]
Oh, thank you!

**Comment by tanyaschlusser** [comment]
Thank you for your help fixing this @alvarouc 🎉 — version 1.0.4 , which fixes this by casting to `uint8` and raising a warning is available now on pypi and conda-forge.
